# Generated by Django 4.1.7 on 2023-03-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
