# Generated by Django 4.1.7 on 2023-03-18 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genres', models.CharField(max_length=100)),
                ('playtime', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('likes', models.PositiveIntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
    ]
