# Generated by Django 4.1.7 on 2023-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p'),
        ),
    ]
